name: Test
on:
  workflow_call:

permissions: read-all

jobs:
  reusable-example:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - macos-26
          - ubuntu-24.04
          - windows-2025
    steps:
      - name: Verify action checksums
        uses: $/.github/actions/ghasum
      - name: Step with pre-script
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
      - name: action
        uses: actions/setup-go@v7.0.0
        with:
          go-version: '1.23'
