name: Test
on:
  push:

permissions: read-all

jobs:
  reusing-1:
    uses: ./.github/workflows/reusable-workflow.yml
  reusing-2:
    uses: $/.github/workflows/reusable-workflow.yml
  test-install:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - macos-26
          - ubuntu-24.04
          - windows-2025
    steps:
      - name: Verify action checksums
        uses: $/.github/actions/ghasum
        with:
          mode: install
      - name: echo PATH
        run: echo "$PATH"
      - name: Use ghasum
        run: ghasum version
  test-verify:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - macos-26
          - ubuntu-24.04
          - windows-2025
    steps:
      - name: Verify action checksums
        uses: $/.github/actions/ghasum
      - name: Step with pre-script
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Step with post-scripts
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 20
      - name: Install dependencies
        run: echo 'success'
