name: Test
on:
  push:

permissions: read-all

env:
  GHASUM: |
    actions/setup-node@v6.0.0 GRqp8XDY/VE7U6CS0j0+ssTCaCaa2ba5wGKAjhRCR1s=
    actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 lqcOZgWyTneOKF0riqdP6+vaHfT8MJqXvjKe4fdsTjs=
    step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf zTn6q6y54XCU92WeEvyJAl8XTI4bE1BVzyIgT9N2lYk=


jobs:
  test-composite:
    runs-on: ubuntu-24.04
    steps:
      - name: Verify action checksums
        uses: $/.github/actions/ghasum-composite
        env: # TODO: avoid?
          GH_TOKEN: ${{ github.token }}
      - name: Step with pre-script
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Step with post-scripts
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 20
      - name: Install dependencies
        run: echo 'success'
  test-go:
    runs-on: ubuntu-24.04
    steps:
      - name: Verify action checksums
        uses: $/.github/actions/ghasum-go
      - name: Step with pre-script
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Step with post-scripts
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 20
      - name: Install dependencies
        run: echo 'success'
  test-node:
    runs-on: ubuntu-24.04
    steps:
      - name: Verify action checksums
        uses: $/.github/actions/ghasum-node
        env: # TODO: avoid?
          GH_TOKEN: ${{ github.token }}
      - name: Step with pre-script
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Step with post-scripts
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 20
      - name: Install dependencies
        run: echo 'success'
